In [9]:
#polynomial regression
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

#data
df = pd.DataFrame({
    "Experience":[1,2,3,4,5]
})
x=df
y= [10,20,50,90,150]
#polyfeature
poly = PolynomialFeatures(degree=2)
x_poly = poly.fit_transform(x)
print(x_poly)

#model
model = LinearRegression()
model.fit(x_poly,y)

#predict
input_data= int(input('Enter the experience:'))
new_data = pd.DataFrame({
    "Experience":[input_data]
})


#convert new data
u_new_data= poly.fit_transform(new_data)
predicted_model=model.predict(u_new_data)
print(predicted_model)



[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]
Enter the experience:5
[149.71428571]
