In [ ]:
#polynomial regression
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

#data
df = pd.DataFrame({
    "Experience":[1,2,3,4,5]
})
x=df
y= [10,20,50,90,150]
#polyfeature
poly = PolynomialFeatures(degree=2)
x_poly = poly.fit_transform(x)
print(x_poly)

#model
model = LinearRegression()
model.fit(x_poly,y)

#predict
input_data= int(input('Enter the experience:'))
new_data = pd.DataFrame({
    "Experience":[input_data]
})


#convert new data
u_new_data= poly.fit_transform(new_data)
predicted_model=model.predict(u_new_data)
print(predicted_model)

plt.plot(x_poly,y)
plt.show()


[[ 1.  1.  1.]
 [ 1.  2.  4.]
 [ 1.  3.  9.]
 [ 1.  4. 16.]
 [ 1.  5. 25.]]


KeyboardInterrupt: Interrupted by user

In [ ]:
#linear Regression -- underfitting

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df=pd.DataFrame({
        "lable":[1,2,3,4,5]
})
x=df
y= [10,20,50,90,150]

#model
model = LinearRegression()
model.fit(x,y)

#predict
input_data= int(input('Enter the LABEL:'))
new_data = pd.DataFrame({
    "lable":[input_data]
})

predicted_data = model.predict(new_data)
print(predicted_data[0])



In [ ]:
#poly regression -- overfitting

import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

df=pd.DataFrame({
        "lable":[1,2,3,4,5]
})
x=df
y= [10,20,50,90,150]

poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)
print(x_poly)

#model
model = LinearRegression()
model.fit(x_poly,y)

#predict
input_data= float(input('Enter the LABEL:'))
new_data = pd.DataFrame({
    "lable":[input_data]
})

#inputdata to poly
u_new_data= poly.fit_transform(new_data)

#prediction
predicted_model=model.predict(u_new_data)
print(predicted_model[0])


[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   4.  16.  64.]
 [  1.   5.  25. 125.]]
Enter the LABEL:5.2
163.3142857142858


In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

df=pd.DataFrame({
    "weight":[120,140,150,170],
    "Size":[6,7,7,8]
})
x=df
y=["apple","apple","Orange","Orange"]

#model
model = DecisionTreeClassifier()
model.fit(x,y)

#prediction data
input_weight= int(input('Enter the weight:'))
input_size= int(input('Enter the size:'))
new_data = pd.DataFrame({
    "weight":[input_weight],
    "Size":[input_size]
})

#prediction
up_new_data=model.predict(new_data)
print(up_new_data[0])

In [ ]:
#pass above 40 and less than 40 ->fail

df=pd.DataFrame({
    "Marks":[10,20,30,40,50,60,70,80],
    "Result":['fail','fail','fail','pass','pass','pass','pass','pass']
})
x=df[['Marks']]
y=df['Result']

#model
model=DecisionTreeClassifier()
model.fit(x,y)

#prediction data
input_data=int(input('Enter the marks: '))
new_data= pd.DataFrame({
    "Marks":[input_data]
})

#prediction
model_predict = model.predict(new_data)
print(model_predict[0])

Enter the marks: 41
pass


In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder

# Dataset
df = pd.DataFrame({
    "Marks": [10, 20, 30, 40, 50, 60, 70, 80],
    "Result": ['fail', 'fail', 'fail', 'pass', 'pass', 'pass', 'pass', 'pass']
})

# Label Encoding
le = LabelEncoder()
df['Result'] = le.fit_transform(df['Result'])

print("Encoded Data:")
print(df)

# Features and Target
x = df[['Marks']]
y = df['Result']

# Model
model = DecisionTreeClassifier(random_state=42)
model.fit(x, y)

# User Input
input_data = int(input("Enter the marks: "))

new_data = pd.DataFrame({
    "Marks": [input_data]
})

# Prediction (Encoded)
prediction = model.predict(new_data)

# Label Decoding
result = le.inverse_transform(prediction)

print("Encoded Prediction:", prediction[0])
print("Final Prediction:", result[0])

Encoded Data:
   Marks  Result
0     10       0
1     20       0
2     30       0
3     40       1
4     50       1
5     60       1
6     70       1
7     80       1
Enter the marks: 40
Encoded Prediction: 1
Final Prediction: pass


In [ ]:
#logistic rgression
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

x= pd.DataFrame({
    "Hours":[1,2,3,4,5,6,7,8,9,10]
})
y=[0,0,0,0,1,1,1,1,1,1]

model=LogisticRegression()
model.fit(x,y)

#prediction
new_data=pd.DataFrame({
    "Hours":[-1]
})

predicted_data=model.predict(new_data)
print(predicted_data)

[0]


In [ ]:
#train test split

from sklearn.model_selection import train_test_split

x=[[1],[2],[3],[4],[5],[6]]
y=[30,40,50,60,70,80]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

print("training feature:")
print(x_train)
print("training target:")
print(y_train)
print("testing feature:")
print(x_test)
print("testing target:")
print(y_test)

training feature:
[[6], [3], [5], [4]]
training target:
[80, 50, 70, 60]
testing feature:
[[1], [2]]
testing target:
[30, 40]


In [ ]:
#linear regression

import pandas as pd
from sklearn.linear_model import LinearRegression

data = {
    "experience":[1,2,3,4,5],
    "salary":[3,5,7,9,11]
}

df=pd.DataFrame(data)
x=df[['experience']]
y=df['salary']

model=LinearRegression()
model.fit(x,y)

new_data = pd.DataFrame({
    "experience":[6]
})

predicted_data=model.predict(new_data)
print(predicted_data[0])

13.0


In [ ]:
#evaluation matrix - > to evaluate that prediction is how much correct
import numpy as np
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

#actual value
y_true=np.array([50,60,75,90,100])

#predicted value
y_pred = np.array=([48,59,72,88,105])

#mean absoutle error
mae=mean_absolute_error(y_true,y_pred)
print(mae)

#mean squared error
mse=mean_squared_error(y_true,y_pred)
print(mse)
#r2 score
r2=r2_score(y_true,y_pred)
print(r2)

#rmse
rmse= np.sqrt(mse)
print(rmse)

2.6
8.6
0.9747058823529412
2.932575659723036


In [1]:
#lasso and ridge regression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error

data={
    "size":[1000,1200,1500,1800,2000,2200,2500,2700,3000,3200],
    "bedrooms":[2,2,3,3,3,4,4,4,5,5],
    "age":[20,18,15,12,10,8,6,5,4,2],
    "price":[30,35,45,50,55,60,68,72,80,85]
}

df=pd.DataFrame(data)
print(df)

#split data into x and y
x=df[['size','bedrooms','age']]
y=df['price']

#train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

ridge_p = Ridge(alpha=1.0)
ridge_p.fit(x_train,y_train)

#prediction
ridge_pred=ridge_p.predict(x_test)
print(ridge_pred)

#mae
ridge_mae=mean_absolute_error(y_test,ridge_pred)
print(ridge_mae)


   size  bedrooms  age  price
0  1000         2   20     30
1  1200         2   18     35
2  1500         3   15     45
3  1800         3   12     50
4  2000         3   10     55
5  2200         4    8     60
6  2500         4    6     68
7  2700         4    5     72
8  3000         5    4     80
9  3200         5    2     85
[80.14635491 35.57736915]
0.3618620315174681


In [5]:
#lasso regression
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error

data={
    "size":[1000,1200,1500,1800,2000,2200,2500,2700,3000,3200],
    "bedrooms":[2,2,3,3,3,4,4,4,5,5],
    "age":[20,18,15,12,10,8,6,5,4,2],
    "price":[30,35,45,50,55,60,68,72,80,85]
}

df=pd.DataFrame(data)
print(df)

#split data into x and y
x=df[['size','bedrooms','age']]
y=df['price']

#train test split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#model
lasso_p = Lasso(alpha=1.0)
lasso_p.fit(x_train,y_train)

#prediction
lasso_pred=lasso_p.predict(x_test)
print(lasso_pred)   #-> intrcept+[(coef1*fea1)+(coef2*fea2)+(coef3*fea3)]

#mae
lasso_mae=mean_absolute_error(y_test,lasso_pred)
print(lasso_mae)

#inercept
print(lasso_p.intercept_)

#coefficient
print(lasso_p.coef_)



   size  bedrooms  age  price
0  1000         2   20     30
1  1200         2   18     35
2  1500         3   15     45
3  1800         3   12     50
4  2000         3   10     55
5  2200         4    8     60
6  2500         4    6     68
7  2700         4    5     72
8  3000         5    4     80
9  3200         5    2     85
[79.8857059  35.75131646]
0.4328052805280507
6.3283901723505736
[0.02451911 0.         0.        ]


In [9]:
#logistic regression
import pandas as pd
from sklearn.linear_model import LogisticRegression

data = pd.DataFrame({
    "Hours":[1,2,3,4,5,6,7,8,9,10],
    "Result":[0,0,0,1,1,1,1,1,1,1]

})
x=data[['Hours']]
y=data['Result']

#model
model=LogisticRegression()
model.fit(x,y)

#prediction
new_data=pd.DataFrame({
    "Hours":[3.2]
})
predicted_data=model.predict(new_data)
print(predicted_data)

#probability
prob_data=model.predict_proba(new_data)
print(prob_data)
#

[0]
[[0.57905959 0.42094041]]


In [10]:
#knn
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier

data=pd.DataFrame({
    "size":[100,110,120,140,150,160],
    "fruits":[0,0,0,1,1,1]
})

x=data[['size']]
y=data['fruits']

#model
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x,y)

#prediction
new_data=pd.DataFrame({
    "size":[1200]

    })

predicted_data=model.predict(new_data)
print(predicted_data)


[1]
