In [ ]:
#creating array from list
#1d list
#import numpy as np
#l#ist=[1,2,3]
#print(list)

#array 1d
#arr = np.array(list)
#print(arr)

#2d list
import numpy as np
l = [[1,23,34],[4,5,6]]
print(l)
l[1][1]= 100
print (l)

arr = np.array(l)
print(arr)
print(arr[1][1])


[[1, 23, 34], [4, 5, 6]]
[[1, 23, 34], [4, 100, 6]]
[[  1  23  34]
 [  4 100   6]]
100


list vs numpy array


In [ ]:
#list
l= [1,2,3]
lm = 2*l
print(lm)

#array
import numpy as np
arr = np.array(l)
#arrm = arr*2
arrm= arr+2
print(arrm)

[1, 2, 3, 1, 2, 3]
[3 4 5]


In [ ]:
#comparison
import numpy as np
import time


# list
start = time.time()
l = [i*2 for i in range(1000000)]
print("list output:",time.time() - start)

# array
start = time.time()
arr = np.array(1000000)*2
print("array output:",time.time() - start)

list output: 0.07632136344909668
array output: 0.0001652240753173828


In [ ]:
#zeroes #ones
import numpy as np
#array 1d
arr = np.zeros(3)
print (arr)

arr1 = np.zeros((3,4))
print(arr1)

arr2 = np.ones((3,4,5))
print(arr2)


[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [ ]:
import numpy as np
arr = np.zeros((3,4))
arr1 = arr+10
print (arr)
print(arr1)
arr2 = np.ones((3,4))
arr3 =arr2 *5
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10. 10. 10. 10.]
 [10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [26]:
#array
import numpy as np
arr = np.arange(11).reshape(11,1)
print("shape:",np.shape(arr))
print("dimension:", np.ndim(arr))
print("size:",np.size(arr))
print("data type:", arr.dtype)

shape: (11, 1)
dimension: 2
size: 11
data type: int64


In [27]:
import numpy as np
# vector 1d list
l = [1,2,3]
print(l)
#vector 1d array
arr = np.array(l)
print(arr)

#matrix 2d list
l = [[1,2,3],[4,5,6]]
print(l)
#matrix 2d array
arr = np.array(l)
print(arr)

#tensor 3d list
l = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(l)
#tensor 3d array
arr = np.array(l)
print(arr)


[1, 2, 3]
[1 2 3]
[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
