array reshaping

In [4]:
#reshape array
import numpy as np
arr = np.arange(12)
up_arr = arr.reshape(3,4)
print (up_arr)

#example 2d
import numpy as np
arr1 = np.arange(14)
arr_1= np.reshape(arr1,(2,7))
print(arr_1)

#example 3d
import numpy as np

arr12 = np.arange(24)
arr_up= np.reshape(arr12,(3,2,4))
print(arr_up)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [11]:
#flatten -> makes copy of original array on updating the updated array does not change original array
import numpy as np
arr= np.arange(12).reshape(3,4)
print(arr)
arr_flat = arr.flatten()
arr_flat[0]=100 #-> does not update original array
print(arr_flat)
print(arr)

#example 3d
import numpy as np
arr1 = np.arange(24).reshape(3,2,4)
print(arr1)
arr_1= arr1.flatten()
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
#ravel -> on changing updated array original array also changes->shares same memory
import numpy as np
#example 2d
arr=np.arange(12).reshape(3,4)
print(arr)
arr_up = arr.ravel()
arr_up[0]=100 #-> updates original array also
print(arr_up)
print(arr)

#example 3d
import numpy as np
arr1 = np.arange(24).reshape(3,2,4)
print(arr1)
arr_1= arr1.ravel()
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[100   1   2   3   4   5   6   7   8   9  10  11]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
#transpose
import numpy as np
arr = np.arange(12).reshape(3,4)
print(arr)
arr_up = arr.transpose()
print(arr_up)

#example transpose 3d
import numpy as np
arr1 = np.arange(24).reshape(3,2,4)
print(arr1)
arr_1= arr1.transpose()
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  8 16]
  [ 4 12 20]]

 [[ 1  9 17]
  [ 5 13 21]]

 [[ 2 10 18]
  [ 6 14 22]]

 [[ 3 11 19]
  [ 7 15 23]]]


numpy array operations

In [27]:
#slicing  for 1d
#import numpy as np
#arr = np.arange(10)
#print(arr)
#up_arr=arr[2:6]
#up_arr=arr[:6]
#print(up_arr)
#print(arr)

#slicing for 2d
#import numpy as np
#arr1 = np.arange(8).reshape(2,4)
#print(arr1)
#up_arr1= arr1[:,-1]
#print(up_arr1)
#print(arr1)

# slicing in 3d
import numpy as np
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr[:1,:1,:1],arr[1:2,2:3,3:4])


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[0]]] [[[23]]]


In [22]:
import numpy as np

# Create a NumPy 2D array
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# Slice rows 1 to 3 and columns 1 to 3
sub_arr = arr[1:3, 1:3]
print (sub_arr)


[[ 6  7]
 [10 11]]


looping in numpy

In [31]:
#while loop
import numpy as np
arr= np.arange(12)
i=0
while i < len(arr):
 # print(arr[i],end=" ")
  i += 1
# while loop 2d

arr1 = np.arange(12).reshape(3,4)

i = 0
while i < len(arr1):
    j = 0
    while j < len(arr1[i]):
        print(arr1[i][j], end=" ")
        j += 1
    print()
    print("\n")
    i += 1

#while loop for 3d


0 1 2 3 


4 5 6 7 


8 9 10 11 




In [36]:
#for loop 1d
import numpy as np
arr = np.arange(12)
for i in arr:
    print(i, end = " ")

#2d array
print("2d array")
import numpy as np
arr1 = np.arange(12).reshape(3,4)
for i in arr1:
    for j in i:
        print(j,end = " ")

#print 3d array
import numpy as np
arr2 = np.arange(24).reshape(2,3,4)
for i in arr2:
  for j in i:
    for k in j:
      print(k, end=" ")
    print()
  print()

0 1 2 3 4 5 6 7 8 9 10 11 2d array
0 1 2 3 4 5 6 7 8 9 10 11 0 1 2 3 
4 5 6 7 
8 9 10 11 

12 13 14 15 
16 17 18 19 
20 21 22 23 

