array reshaping

In [4]:
#reshape array
import numpy as np
arr = np.arange(12)
up_arr = arr.reshape(3,4)
print (up_arr)

#example 2d
import numpy as np
arr1 = np.arange(14)
arr_1= np.reshape(arr1,(2,7))
print(arr_1)

#example 3d
import numpy as np

arr12 = np.arange(24)
arr_up= np.reshape(arr12,(3,2,4))
print(arr_up)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [6]:
#flatten
import numpy as np
arr= np.arange(12).reshape(3,4)
print(arr)
arr_flat = arr.flatten()
print(arr_flat)

#example 3d
import numpy as np
arr1 = np.arange(24).reshape(3,2,4)
print(arr1)
arr_1= arr1.flatten()
print(arr_1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
