Sorting

In [10]:
#sorting
import numpy as np
arr= np.array([10,24,35,60,7,8])
print(arr)
up_arr= np.sort(arr)
print(up_arr)

#2d
#axis=0 -> for cols
#axis=1 -> for rows
import numpy as np
arr1 = np.array([[13,5,35],[4,54,60]])
#print(arr1)
arr_s= np.sort(arr1,axis =0)#->bydefault it is row wise sorting
#print(arr_s)

#example for 2d
import numpy as np
arr2 = np.array ([[24,68,2],[34,35,6]])
print(arr2)
arr_so= np.sort(arr2,axis=0)
print(arr_so)

#sorting in descending order

[10 24 35 60  7  8]
[ 7  8 10 24 35 60]
[[24 68  2]
 [34 35  6]]
[[24 35  2]
 [34 68  6]]


filter

In [13]:
#filter
#1d
import numpy as np
arr= np.array([2,4,55,6,84,9])
#print(arr)
arr_f=arr[arr<60]
#print(arr_f)

#example
import numpy as np
arr1 = np.array ([2,4,56,78,35,64])
print(arr1)
arr_fi = arr1[arr1%2==0]
print(arr_fi)

[ 2  4 56 78 35 64]
[ 2  4 56 78 64]


fancy indexing vs np.where()

In [17]:
#fancy indexing
import numpy as np
arr= np.array([12,34,24,3,5])
print (arr)
arr_f=  arr [[0,4]] #-> 0 index value , 4 index value
print(arr_f)

#example
import numpy as np
arr1 = np.array ([[12,234,3,53],
                 [34,6,78,25]])
print(arr1)
arr_fa= arr1[[0,1]]
print(arr_fa)

[12 34 24  3  5]
[12  5]
[[ 12 234   3  53]
 [ 34   6  78  25]]
[[ 12 234   3  53]
 [ 34   6  78  25]]


In [19]:
#np.where
import numpy as np
arr= np.array ([2,5,36,57,32])
print(arr)
arr_w= np.where(arr < 40, "true", "false")#-> condition , : true : false
print(arr_w)

#exaple 1
import numpy as np
arr1 = np.array ([[12,234,3,53],
                 [34,6,78,25]])
print(arr1)
arr_wa= np.where(arr1%2==0, "true", "false")
print(arr_wa)
#

[ 2  5 36 57 32]
['true' 'true' 'true' 'false' 'true']
[[ 12 234   3  53]
 [ 34   6  78  25]]
[['true' 'true' 'false' 'false']
 ['true' 'true' 'true' 'false']]


cancatenation

In [25]:
#concatenate
import numpy as np
arr= np.array([2,4,5,3])
arr1 = np.array ([1,2,3,4])
arr_new= np.concatenate((arr,arr1))
#print(arr_new)

#example 2d
import numpy as np
arr2= np.array([[3,4,7,2],[5,8,9,14]])
arr3= np.array ([[32,3,6,4],[7,86,47,3]])
arr_new1= np.concatenate((arr2,arr3),axis=1)
print(arr_new1)
#

[[ 3  4  7  2 32  3  6  4]
 [ 5  8  9 14  7 86 47  3]]


statistical function
