Sorting

In [10]:
#sorting
import numpy as np
arr= np.array([10,24,35,60,7,8])
print(arr)
up_arr= np.sort(arr)
print(up_arr)

#2d
#axis=0 -> for cols
#axis=1 -> for rows
import numpy as np
arr1 = np.array([[13,5,35],[4,54,60]])
#print(arr1)
arr_s= np.sort(arr1,axis =0)#->bydefault it is row wise sorting
#print(arr_s)

#example for 2d
import numpy as np
arr2 = np.array ([[24,68,2],[34,35,6]])
print(arr2)
arr_so= np.sort(arr2,axis=0)
print(arr_so)

#sorting in descending order

[10 24 35 60  7  8]
[ 7  8 10 24 35 60]
[[24 68  2]
 [34 35  6]]
[[24 35  2]
 [34 68  6]]


filter

In [13]:
#filter
#1d
import numpy as np
arr= np.array([2,4,55,6,84,9])
#print(arr)
arr_f=arr[arr<60]
#print(arr_f)

#example
import numpy as np
arr1 = np.array ([2,4,56,78,35,64])
print(arr1)
arr_fi = arr1[arr1%2==0]
print(arr_fi)

[ 2  4 56 78 35 64]
[ 2  4 56 78 64]


fancy indexing vs np.where()

In [17]:
#fancy indexing
import numpy as np
arr= np.array([12,34,24,3,5])
print (arr)
arr_f=  arr [[0,4]] #-> 0 index value , 4 index value
print(arr_f)

#example
import numpy as np
arr1 = np.array ([[12,234,3,53],
                 [34,6,78,25]])
print(arr1)
arr_fa= arr1[[0,1]]
print(arr_fa)

[12 34 24  3  5]
[12  5]
[[ 12 234   3  53]
 [ 34   6  78  25]]
[[ 12 234   3  53]
 [ 34   6  78  25]]


In [29]:
#np.where
import numpy as np
arr= np.array ([2,5,36,57,32])
print(arr)
arr_w= np.where(arr < 40, "true", "false")#-> condition , : true : false
print(arr_w)

#exaple 1
import numpy as np
arr1 = np.array ([[12,234,3,53],
                 [34,6,78,25]])
print(arr1)
arr_wa= np.where(arr1%2==0, "true", "false")
print(arr_wa)
print(arr1)


[ 2  5 36 57 32]
['true' 'true' 'true' 'false' 'true']
[[ 12 234   3  53]
 [ 34   6  78  25]]
[['true' 'true' 'false' 'false']
 ['true' 'true' 'true' 'false']]
[[ 12 234   3  53]
 [ 34   6  78  25]]


cancatenation

In [27]:
#concatenate
import numpy as np
arr= np.array([2,4,5,3])
arr1 = np.array ([1,2,3,4])
arr_new= np.concatenate((arr,arr1))
#print(arr_new)

#example 2d
import numpy as np
arr2= np.array([[3,4,7,2],[5,8,9,14]])
arr3= np.array ([[32,3,6,4],[7,86,47,3]])
arr_new1= np.concatenate((arr2,arr3),axis=1)
arr_new2= np.concatenate((arr2,arr3),axis=0)
print(arr_new1)
print(arr_new2)
#

[[ 3  4  7  2 32  3  6  4]
 [ 5  8  9 14  7 86 47  3]]
[[ 3  4  7  2]
 [ 5  8  9 14]
 [32  3  6  4]
 [ 7 86 47  3]]


statistical function
1. np.sum(a) -> Sum of all elements
2. np.mean(a) -> Average = Sum of elements / Number of elements
3. np.median(a) -> Middle value after sorting
4. np.min(a) -> Smallest value in array
5. np.max(a) -> Largest value in array
6. np.var(a) mean,difference,square,average | (sum = ddof) -> divide by array length
7. np.std(a) -> Standard Deviation = √Variance -> Measures spread of data
8. np.prod(a) -> Multiplication of all elements
9. np.cumsum(a) -> Cumulative (running) sum
10. np.cumprod(a) -> Cumulative (running) product
11. np.argmin(a) -> Index position of minimum value
12. np.argmax(a) -> Index position of maximum value
13. np.abs(a) -> Converts negative values to positive -> Absolute value (distance from zero)
14. np.unique(a) -> Returns unique values only -> Removes duplicates
15. np.percentile(a, 50) -> Finds percentage-based value -> 50th percentile = Median
16. np.quantile(a, 0.5) -> Similar to percentile -> 0.5 = 50%
17. np.ptp(a) -> Range = Max - Min
18. np.any(a) -> True if at least one value is True

In [41]:
#question no 1
import numpy as np
arr= np.array ([2,8,4,5,7])
arr_sum= np.sum(arr)
print(arr_sum)

#question no 2
import numpy as np
arr1 = np .array(arr)
arr_mean= np.mean(arr1)
print(arr_mean)

#question no 3
arr2= np.array (arr)
arr_median= np.median(arr2)
print(arr_median)

#question no 4
arr3= np.array (arr)
arr_min= np.min(arr3)
print(arr_min)

#question no 5
arr4 = np.array (arr)
arr_max= np.max(arr4)
print(arr_max)
#question no 6


26
5.2
5.0
2
8
